name: CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  continuous_integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Verify Build
        run: go build ./cmd/gitpoll

      - name: Unit Test
        run: go test ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: Dependency Check
        uses: golang/govulncheck-action@v1
        with:
          go-version-file: 'go.mod'
          repo-checkout: false

      - name: Security Scan
        uses: securego/gosec@master
        with:
          args: ./...
